"""
Complete RAG: retrieval + generation
Goal: Combine everything covered so far into a system that answers questions
based on the actual document content, rather than what the LLM "thinks" it knows.
"""

from dotenv import load_dotenv
import os
from langchain_google_genai import GoogleGenerativeAIEmbeddings
from langchain_chroma import Chroma
from loaders import load_PDF

load_dotenv()

from langchain_google_genai import ChatGoogleGenerativeAI, GoogleGenerativeAIEmbeddings
from langchain_chroma import Chroma
# PromptTemplate contains plain text, while ChatPromptTemplate represents chat
# messages with roles such as system and human.
from langchain_core.prompts import ChatPromptTemplate, PromptTemplate
from langchain_core.output_parsers import StrOutputParser
from langchain_core.runnables import RunnablePassthrough

AISTUDIO_APIKEY = os.getenv('AISTUDIO_APIKEY')
COLLECTION_NAME = os.getenv('MULTIPLE_SOURCES_COLLECTION_NAME')
SQLITE_DISK_DIRECTORY = os.getenv('SQLITE_DISK_DIRECTORY')
CHROMADB_EMBEDDINGS_MODEL = os.getenv('CHROMADB_EMBEDDINGS_MODEL')
GEMINI_MODEL = os.getenv('GEMINI_MODEL')
PLAYER = "Nikola Jokic"
# That goal question mixes both PDFs information
GOAL_QUESTION = f"Haz un resumen de los logros históricos de {PLAYER} esta temporada, incluyendo tanto sus liderazgos estadísticos como sus triples-dobles en carrera."

# Chroma needs the same model to convert each new question into a vector that
# can be compared with the stored documents. This does not recalculate or
# store the document embeddings again.
embeddings = GoogleGenerativeAIEmbeddings(
    model=CHROMADB_EMBEDDINGS_MODEL, 
    google_api_key=AISTUDIO_APIKEY
)

# Load existing vector database (no need to re-index it).
vectorstore = Chroma(
    persist_directory="./chroma_db",
    embedding_function=embeddings,
    collection_name=COLLECTION_NAME
)

# Testing similarity search before using AI
# question = f"¿De qué hablan los documentos sobre {PLAYER}?"
# resultados = vectorstore.similarity_search(question, k=5) # k is number of splits to return

# print("*****************")
# print(f"Consulting collection {COLLECTION_NAME}")
# print("*****************")
# print("Result:")
# print(f"\nMost relevant chunks for: '{question}'\n")
# for i, doc in enumerate(resultados, 1):
#     print(f"--- Chunk {i} ---")
#     print(doc.page_content[:300])
#     print()

# Retriever is the component that searches for relevant chunks
retriever = vectorstore.as_retriever(search_kwargs={"k": 5})

# Check chromaDB chunks retrieved multi-source
fragmentos_encontrados = retriever.invoke(GOAL_QUESTION)
for i, doc in enumerate(fragmentos_encontrados, 1):
    print(f"--- Chunk {i} — Source: {doc.metadata['source']} ---")
    print(doc.page_content[:150])
    print()

# Prompt that combines the question and the retrieved context
prompt = ChatPromptTemplate.from_template(
    """
    Responde la pregunta basándote ÚNICAMENTE en el siguiente contexto.
    Si la respuesta no está en el contexto, di que no lo sabes.

    Contexto: {contexto}
    Pregunta: {pregunta}
""")

llm = ChatGoogleGenerativeAI(
    model="gemini-3.6-flash",
    google_api_key=AISTUDIO_APIKEY
)

# 4. Helper function to convert the retrieved documents into plain text
def document_tostring(docs):
    return "\n\n".join(doc.page_content for doc in docs)

# 5. The complete RAG chain:
# - "pregunta" is passed through unchanged
# - "contexto" is generated by searching with the retriever and formatting the result
rag_chain = (
    {"contexto": retriever | document_tostring, "pregunta": RunnablePassthrough()}
    | prompt
    | llm
    | StrOutputParser()
)

# Executing
respuesta = rag_chain.invoke(GOAL_QUESTION)

print("*****************")
print(f"Consulting Gemini with RAG data stored in {COLLECTION_NAME}")
print("*****************")
print(f"Question: {GOAL_QUESTION}")
print(f"Answer: {respuesta}")